service: cloudwatch-log-publisher
frameworkVersion: '3'

provider:
  name: aws
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}
  runtime: python3.9
  logRetentionInDays: 14
  memorySize: 128

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  handler:
    handler: cloudwatch_log_publisher.handler.handle_log
    environment:
      SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
      SLACK_CHANNEL: ${env:SLACK_CHANNEL}
      MAX_MESSAGE_LENGTH: ${env:MAX_MESSAGE_LENGTH}

resources:
  Resources:
    CWLambdaPermission:
      Type: AWS::Lambda::Permission
      DependsOn:
        - HandlerLambdaFunction
      Properties:
        FunctionName: !Sub "${AWS::StackName}-handler"
        Action: lambda:InvokeFunction
        Principal: logs.amazonaws.com

plugins:
   - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - .venv/**
